<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit353052ced14c68dd8ce9de947d2dabd8
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PdoConnect\\DB\\' => 14,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PdoConnect\\DB\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $prefixesPsr0 = array (
        'R' => 
        array (
            'Rain' => 
            array (
                0 => __DIR__ . '/..' . '/rain/raintpl/library',
            ),
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit353052ced14c68dd8ce9de947d2dabd8::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit353052ced14c68dd8ce9de947d2dabd8::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit353052ced14c68dd8ce9de947d2dabd8::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit353052ced14c68dd8ce9de947d2dabd8::$classMap;

        }, null, ClassLoader::class);
    }
}
